In [1]:
pip install opencv-contrib-python==4.5.3.56

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2 as cv # computer vision library for image processing
import pyttsx3 # for text to speech conversion
import numpy as np

In [3]:
# Opening the camera to check its pixel width
# Dividing the camera frame into 3 vertical parts/strips (left/middle/right). 
# Used later for sensing object direction wrt the camera screen

n_rows = 1
n_images_per_row = 3

cap = cv.VideoCapture(0)

ret, frame = cap.read()
height,width,ch = frame.shape

roi_height = height // n_rows
roi_width = width // n_images_per_row

print("Width =", width)
print("Width/3 =", roi_width)

Width = 640
Width/3 = 213


In [4]:
def text_to_speech(string):
    text_speech = pyttsx3.init()
    text_speech.say(string)
    text_speech.runAndWait()

In [5]:
# object detector function /method
def object_detector(image):
    classes, scores, boxes = model.detect(image, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)
    # creating empty list to add objects data
    data_list = []
    for (classid, score, box) in zip(classes, scores, boxes):
        
        # define color of each, object based on its class id
        '''
        80 object names are stored in classes.txt and 6 colours are stored in var COLORS
        For 1st object name (person) -> 0 % 6 = 0. So colour[0] = RED will be chosen
        For 2nd object name (bicycle) -> 1 % 6 = 1. So colour[1] = PURPLE will be chosen
        And so on...
        '''
        color= COLORS[int(classid) % len(COLORS)]
        
        # label -> stores class id and confidence score
        label = "%s : %f" % (class_names[classid[0]], score)
        print(label)

        # draw rectangle on and label on object
        cv.rectangle(image, box, color, 2)
        cv.putText(image, label, (box[0], box[1]-14), FONTS, 0.5, color, 2)
        
        # print("box values =", box)
        # prints [  3  67 425 413] (Example)
        '''
        3 is the x-coordinate of the top-left corner of the bounding box.
        67 is the y-coordinate of the top-left corner of the bounding box.
        425 is the x-coordinate of the bottom-right corner of the bounding box.
        413 is the y-coordinate of the bottom-right corner of the bounding box.
        '''
        
        # finding the central coordinates of bounding box
        mid_x = (box[0] + box[2]) / 2
        # mid_y = (box[1] + box[3]) / 2
        
        # plotting a point at the centre of the bounding box
        # cv.circle(frame, (mid_x, mid_y), 5, (255, 0, 255), cv.FILLED)
        
        # finding the x coordinates of the frames 
        right_end_of_frame1 = roi_width
        right_end_of_frame2 = 2*roi_width
        # right_end_of_frame3 = right_end_of_frame2 + roi_width
        
        #print("Right end of frame 1:", right_end_of_frame1)
        #print("Right end of frame 2:", right_end_of_frame2)
        
        # if the central coordinates lie in the the left/right/middle frame
        if(mid_x < right_end_of_frame1):
            text_to_speech('SLIGHTLY ON YOUR LEFT')
        elif(mid_x > right_end_of_frame1 and mid_x < right_end_of_frame2):
            text_to_speech('IN FRONT OF YOU')
        elif(mid_x > right_end_of_frame2):
            text_to_speech('SLIGHTLY ON YOUR RIGHT')
        
        # getting the data 
        # 1: class name  2: object width in pixels, 3: position where have to draw text(distance)
        if classid == 0: # person class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 67: # cell phone class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        
        elif classid == 1: # bicycle class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 2: # car class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 3: # motorbike class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 5: # bus class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 6: # train class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 7: # truck class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 13: # bench class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 15: # cat class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 16: # dog class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 19: # cow class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 39: # bottle class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 56: # chair class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 57: # sofa class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 59: # bed class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 60: # dining table class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 61: # toilet class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 62: # tvmonitor class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        elif classid == 63: # laptop class id
            data_list.append([class_names[classid[0]], box[2], (box[0], box[1]-2)])
        
    return data_list

In [6]:
# FOR FINDING FOCAL LENGTH OF CAM LENS
def focal_length_finder (measured_distance, real_width, width_in_rf):
    focal_length = (width_in_rf * measured_distance) / real_width
    print("FOCAL LENGTH: ", focal_length)
    # focal_length = 560
    return focal_length

In [7]:
# FOR FINDING DISTANCE OF OBJECT FROM CAM
def distance_finder(focal_length, real_object_width, width_in_frame):
    distance = (real_object_width * focal_length) / width_in_frame
    return distance

In [8]:
# Distance constants 
KNOWN_DISTANCE = 114.3 #CENTIMETERS
PERSON_WIDTH = 37 #CENTIMETERS
MOBILE_WIDTH = 7 #CENTIMETERS
BOTTLE_WIDTH = 8
BICYCLE_WIDTH = 67.5
CAR_WIDTH = 177
MOTORBIKE_WIDTH = 82.5
BUS_WIDTH = 90
BENCH_WIDTH = 129.5
CAT_WIDTH = 46
DOG_WIDTH = 51
COW_WIDTH = 183
CHAIR_WIDTH = 43
SOFA_WIDTH = 150
BED_WIDTH = 190
DINING_TABLE_WIDTH = 96.5
TOILET_WIDTH = 51
TV_WIDTH = 100
LAPTOP_WIDTH = 14
TRUCK_WIDTH = 198

# Object detector constant 
CONFIDENCE_THRESHOLD = 0.5
NMS_THRESHOLD = 0.3

# colors for object detected
COLORS = [(255,0,0),(255,0,255),(0, 255, 255), (255, 255, 0), (0, 255, 0), (255, 0, 0)]
# COLORS = [red, purple, cyan, brown, green, red] 

GREEN =(0,255,0) # To show the distance text above the object in GREEN
BLACK =(0,0,0) # To show the bounding box (rectangle) in BLACK

# defining fonts 
FONTS = cv.FONT_HERSHEY_COMPLEX

# getting class names from classes.txt file 
class_names = []
#with open("C:\\Users\\KIIT\\MyPython\\PROJECTS\\object_detection+dist\\Yolov4-Detector-and-Distance-Estimator-master\\classes.txt", "r") as f:
with open("classes.txt", "r") as f:
    class_names = [cname.strip() for cname in f.readlines()]

# setting up opencv net

yoloNet = cv.dnn.readNet('yolov4-tiny.weights', 'yolov4-tiny.cfg')
# Reads deep learning network represented in one of the supported formats.
# For more info, check the links below:
# https://docs.opencv.org/3.4/d6/d0f/group__dnn.html#ga3b34fe7a29494a6a4295c169a7d32422
# https://stackoverflow.com/questions/50390836/understanding-darknets-yolo-cfg-config-files

'''
yoloNet.setPreferableBackend(cv.dnn.DNN_BACKEND_CUDA): This line sets the preferable backend for the YOLO 
neural network to CUDA. CUDA is a parallel computing platform and application programming interface (API) 
model created by NVIDIA. Using CUDA can significantly accelerate computations on NVIDIA GPUs (Graphics 
Processing Units). In this context, it means that the YOLO network will try to utilize CUDA for faster inference.

yoloNet.setPreferableTarget(cv.dnn.DNN_TARGET_CUDA_FP16): This line sets the preferable target for the YOLO 
neural network to CUDA with FP16 precision. FP16 (half-precision floating-point) is a data type that uses 16 
bits to represent a floating-point number, providing a compromise between precision and computational efficiency. 
Using FP16 can further speed up computations on compatible GPUs.
'''
yoloNet.setPreferableBackend(cv.dnn.DNN_BACKEND_CUDA)
yoloNet.setPreferableTarget(cv.dnn.DNN_TARGET_CUDA_FP16)

model = cv.dnn_DetectionModel(yoloNet)

'''
scale -> scale factor (1/255 to scale the pixel values to [0..1])
size -> 416x416 square image

(swapBR=True) -> since OpenCV uses BGR. 
    OpenCV assumes images are in BGR channel order; 
    however, the `mean` value assumes we are using RGB order. 
    To resolve this discrepancy we can swap the R and B channels in image
    by setting this value to `True`.
    By default OpenCV performs this channel swapping for us.
'''
model.setInputParams(size=(416, 416), scale=1/255, swapRB=True)

In [9]:
#FINDING THE FOCAL LENGTH THROUGH THE REFERENCE IMAGES
# reading the reference image from dir 
ref_person = cv.imread('ReferenceImages/image14.png')
ref_mobile = cv.imread('ReferenceImages/image4.png')

mobile_data = object_detector(ref_mobile)
'''
displays [['person', 440, (50, 134)], ['cell phone', 72, (206, 296)]]
440 -> pixel width of person ; (50, 134) -> coordinates of person in image
72 -> pixel width of person ; (206, 296) -> coordinates of cell phone in image
'''
print(mobile_data)
'''
[['person', 440, (50, 134)], ['cell phone', 72, (206, 296)]]
If we check indices [1][1] => 72
So mobile_data[1][1] = 72
'''
mobile_width_in_rf = mobile_data[1][1]
person_data = object_detector(ref_person)

'''
displays [['person', 367, (135, 134)]]
'''
print(person_data)
person_width_in_rf = person_data[0][1]

print(f"Person width in pixels : {person_width_in_rf}) mobile width in pixel: {mobile_width_in_rf}")
# finding focal length 
focal_length = focal_length_finder(KNOWN_DISTANCE, PERSON_WIDTH, person_width_in_rf)
#focal_length_mobile = focal_length_finder(KNOWN_DISTANCE, MOBILE_WIDTH, mobile_width_in_rf)

person : 0.887720
[['person', 440, (50, 134)]]
cell phone : 0.923403
[['person', 440, (50, 134)], ['cell phone', 72, (206, 296)]]
[['person', 440, (50, 134)], ['cell phone', 72, (206, 296)]]
person : 0.910768
[['person', 367, (135, 134)]]
[['person', 367, (135, 134)]]
Person width in pixels : 367) mobile width in pixel: 72
FOCAL LENGTH:  1133.7324324324325


In [10]:
def calc_announce_store_dist(obj_info, width):
    # print(obj_info)
    # typecasting to int and removing decimals
    dist_cm = distance_finder(focal_length, width, obj_info[1])
    dist_m = dist_cm / 100
    # use to limit no. of digits after decimal
    approx_dist = round(dist_m, 2)
    dist_text = f'{obj_info[0]} detected {approx_dist} meters'
    text_to_speech(dist_text)
    return approx_dist # required for drawing bounding box later

In [11]:
'''
def split_rename_screen(n_rows, n_images_per_row, roi_height, roi_width):
    
    images = []
        
    for x in range (0,n_rows):
        for y in range (0,n_images_per_row):
            
#             [[[213 202 199]
#               [212 201 199]
#               [212 202 201]
#               ...
#               [226 210 211]
#               [226 210 210]
#               [224 209 209]]
    
            tmp_image = frame[int (x*roi_height) : int ((x+1)*roi_height), int (y*roi_width) : int ((y+1)*roi_width)]
            images.append(tmp_image)
            #print(tmp_image)
    
    # Display the resulting sub-frame
    direction_names = ['left','center','right'] # reference for determining the direction 
    direction = 0 # pointer to iterate the direction array
    for x in range(0, n_rows):
        for y in range(0, n_images_per_row):
                
            cv.imshow(direction_names[direction] , images[x*n_images_per_row+y])
            cv.moveWindow(direction_names[direction], 100+(y*roi_width), 50+(x*roi_height))
            direction = direction + 1
                
            # cv.imshow(str (x*n_images_per_row+y+1), images[x*n_images_per_row+y])
            # cv.moveWindow(str (x*n_images_per_row+y+1), 100+(y*roi_width), 50+(x*roi_height))
'''

"\ndef split_rename_screen(n_rows, n_images_per_row, roi_height, roi_width):\n    \n    images = []\n        \n    for x in range (0,n_rows):\n        for y in range (0,n_images_per_row):\n            \n#             [[[213 202 199]\n#               [212 201 199]\n#               [212 202 201]\n#               ...\n#               [226 210 211]\n#               [226 210 210]\n#               [224 209 209]]\n    \n            tmp_image = frame[int (x*roi_height) : int ((x+1)*roi_height), int (y*roi_width) : int ((y+1)*roi_width)]\n            images.append(tmp_image)\n            #print(tmp_image)\n    \n    # Display the resulting sub-frame\n    direction_names = ['left','center','right'] # reference for determining the direction \n    direction = 0 # pointer to iterate the direction array\n    for x in range(0, n_rows):\n        for y in range(0, n_images_per_row):\n                \n            cv.imshow(direction_names[direction] , images[x*n_images_per_row+y])\n            cv.moveW

In [12]:
# ACTIVATING AND IMPLEMENTING IN CAMERA

cap = cv.VideoCapture(0) # capturing using cam of pc
n_rows = 1
n_images_per_row = 3

while True:
    ret, frame = cap.read() # inbuilt function for capturing image frame using camera
    height,width,ch = frame.shape
    
    roi_height = height // n_rows
    roi_width = width // n_images_per_row
    
    '''
    if a person comes in front of the camera, variable data stores 
    [['person', 532, (54, 124)]]
    Same for other objects
    '''
    data = object_detector(frame) 
    #print(data)
    
    for d in data:
        
        if d[0] == 'person':
            x, y = d[2]
            distance = calc_announce_store_dist(d, PERSON_WIDTH)
        
        elif d[0] == 'cell phone':
            x, y = d[2]
            distance = calc_announce_store_dist(d, MOBILE_WIDTH)
            
        elif d[0] == 'bottle':
            x, y = d[2]
            distance = calc_announce_store_dist(d, BOTTLE_WIDTH)
            
        elif d[0] == 'bicycle':
            x, y = d[2]
            distance = calc_announce_store_dist(d, BICYCLE_WIDTH)
        
        elif d[0] == 'car':
            x, y = d[2]
            distance = calc_announce_store_dist(d, CAR_WIDTH)
            
        elif d[0] == 'motorbike':
            x, y = d[2]
            distance = calc_announce_store_dist(d, MOTORBIKE_WIDTH)
        
        elif d[0] == 'bus':
            x, y = d[2]
            distance = calc_announce_store_dist(d, BUS_WIDTH)
        
        elif d[0] == 'train':
            x, y = d[2]
            distance = calc_announce_store_dist(d, TRAIN_WIDTH)
        
        elif d[0] == 'truck':
            x, y = d[2]
            distance = calc_announce_store_dist(d, TRUCK_WIDTH)
        
        elif d[0] == 'bench':
            x, y = d[2]
            distance = calc_announce_store_dist(d, BENCH_WIDTH)
            
        elif d[0] == 'cat':
            x, y = d[2]
            distance = calc_announce_store_dist(d, CAT_WIDTH)
            
        elif d[0] == 'dog':
            x, y = d[2]
            distance = calc_announce_store_dist(d, DOG_WIDTH)
        
        elif d[0] == 'cow':
            x, y = d[2]
            distance = calc_announce_store_dist(d, COW_WIDTH)
        
        elif d[0] == 'chair':
            x, y = d[2]
            distance = calc_announce_store_dist(d, CHAIR_WIDTH)
        
        elif d[0] == 'sofa':
            x, y = d[2]
            distance = calc_announce_store_dist(d, SOFA_WIDTH)
        
        elif d[0] == 'bed':
            x, y = d[2]
            distance = calc_announce_store_dist(d, BED_WIDTH)
        
        elif d[0] == 'diningtable':
            x, y = d[2]
            distance = calc_announce_store_dist(d, DINING_TABLE_WIDTH)
        
        elif d[0] == 'toilet':
            x, y = d[2]
            distance = calc_announce_store_dist(d, TOILET_WIDTH)
        
        elif d[0] == 'tvmonitor':
            x, y = d[2]
            distance = calc_announce_store_dist(d, TV_WIDTH)
        
        elif d[0] == 'laptop':
            x, y = d[2]
            distance = calc_announce_store_dist(d, LAPTOP_WIDTH)
        
        # splits the screen into 3 vertical divisions
        # split_rename_screen(n_rows, n_images_per_row, roi_height, roi_width)
        
        #announce_direction()
        
        #printf("Bounding Box: Left=%d, Top=%d, Right=%d, Bottom=%d\n", left, top, right, bot); 
        #draw_box_width(im, left, top, right, bot, width, red, green, blue);
        
        # black rectangle at the upper left corner of the bounding box to display object distance
        cv.rectangle(frame, (x, y-3), (x+150, y+23), BLACK, -1)
        # green text inside the rectangle
        cv.putText(frame, f'DIST: {round(distance, 0)} M', (x+5,y+13), FONTS, 0.48, GREEN, 2)    
        
    cv.imshow('frame', frame)
    
    key = cv.waitKey(1)
    if key == ord('q'):
        break
cv.destroyAllWindows()
cap.release()

person : 0.514328
[['person', 426, (107, 118)]]
person : 0.523907
[['person', 449, (99, 63)]]
person : 0.540398
[['person', 491, (75, 124)]]
person : 0.585566
[['person', 505, (68, 121)]]
person : 0.558009
[['person', 381, (32, 70)]]
person : 0.511805
[['person', 478, (31, 68)]]
person : 0.504179
[['person', 482, (29, 68)]]
person : 0.636484
[['person', 483, (76, 125)]]
person : 0.540434
[['person', 498, (22, 121)]]
person : 0.546428
[['person', 506, (17, 122)]]
